### ISSUE TITLE
Question: How to get credit card details?

### ISSUE THREAD

**Issue by mariusbolik** [fresha/capacitor-plugin-applepay#7]
Hello,

just a short question. I receive the following response from the plugin:
```
{
  paymentData: "eyJ2ZXJzaW9uIjoiRUNfdjEiLCJkYXRhIjoibDZlQ3pkVGpYcVAM3RmNGhBUnVQTU91RThDdG8rYzpRTHNZbW1UOENgreG8xbmxqQ0REajRTeFZ4U0cxZ1pCRWVX…",
  paymentMethod: {
  network: "Visa",
   billingAddress: {},
   displayName: "Visa 4016"
},
  transactionIdentifier: "1F550CDE07135EE9E59C91A66C518FFAA670753B4EC58BC02447711E68ED9CE8"
}
```

How can I get the credit card information to send them to Stripe?

Regards,
Marius

**Comment by kondratk** [comment]
Hi Marius,
In general, you don't get card information from Apple pay. You only get the token you've mentioned. This should be passed to your backend, and then to Stripe API.

I've quickly checked Stripe docs and it looks like they wrap their APIs with dedicated SDKs, what makes things harder. It would be the best if you could ask their support how you can use their APIs with pure PKPaymentRequest from Apple Pay SDKs- without using Stripe iOS framework. This plugin basically wraps Apples SDK, so that's how you access token directly- without third party SDKs.

Let me know if Stripe answers anything useful, so I can add it to docs. I've tested the plugin with Adyen, as they provide such APIs.

**Comment by mariusbolik** [comment]
Hi Kondrat,

thank you for the prompt response. I'll let you know!
